#!/bin/sh

echo "You must be on a department machine, within the cs32 repo in cs32/site to use this script - otherwise it will not update the site"
echo "It will also immediately update the whole website - be sure you're ready to run this script"
echo "If you are not ready, please quit this script now (control-c)."
echo "To confirm you would like to continue, type any input."
read input_variable

WWW=/course/cs0320/www
cp -r * $WWW
rm $WWW/update-site $WWW/README.md
chmod -R 775 $WWW/*

echo "done!"
